%YAML:1.0
video_type: 2
filter: 6
window_size: 15
bb_path:  bb.txt
video_path: /home/hugo/Documents/Mestrado/alov_dataset/alov300/videos/03-Specularity/03-Specularity_video00012/lista.list
init_path: /home/hugo/Documents/Mestrado/alov_dataset/alov300/anotacao/03-Specularity/inicial/03-Specularity_video00012.ann.txt
gt_path: /home/hugo/Documents/Mestrado/alov_dataset/alov300/anotacao/03-Specularity/03-Specularity_video00012.ann
detect: 1
track: 1
detect_failure: 1
show: 1
repeat_video: 0
print_status: 1
valid: 0
conf: 0

